// lib/documents/pdfRenderer.ts
import { PDFDocument, StandardFonts, rgb, PageSizes } from 'pdf-lib';
import { ContractTemplate } from '../../types/template';
import { interpolateFields } from './fieldExtractor';

function wrapText(text: string, maxWidth: number, font: any, fontSize: number): string[] {
  const paragraphs = text.split(/\r?\n/);
  const lines: string[] = [];

  for (const paragraph of paragraphs) {
    if (paragraph.trim() === '') {
      lines.push(''); // blank line
      continue;
    }
    const words = paragraph.split(' ');
    let currentLine = '';
    for (const word of words) {
      const testLine = currentLine ? `${currentLine} ${word}` : word;
      const width = font.widthOfTextAtSize(testLine, fontSize);
      if (width > maxWidth) {
        lines.push(currentLine);
        currentLine = word;
      } else {
        currentLine = testLine;
      }
    }
    if (currentLine) {
      lines.push(currentLine);
    }
  }
  return lines;
}

function addFooter(pdfDoc: PDFDocument, brandName: string, font: any) {
  const pages = pdfDoc.getPages();
  const totalPages = pages.length;
  pages.forEach((page, index) => {
    const { width } = page.getSize();
    
    // Left: Brand footer
    page.drawText(`Generated by ${brandName} — not legal advice`, {
      x: 72,
      y: 36,
      font,
      size: 9,
      color: rgb(0.48, 0.57, 0.66),
    });

    // Right: Page numbers
    const pageNumText = `Page ${index + 1} of ${totalPages}`;
    page.drawText(pageNumText, {
      x: width - 72 - font.widthOfTextAtSize(pageNumText, 9),
      y: 36,
      font,
      size: 9,
      color: rgb(0.48, 0.57, 0.66),
    });
  });
}

export async function generatePdf(
  template: ContractTemplate,
  fieldValues: Record<string, string>,
  enabledClauses: Record<string, boolean>,
  aiCustomizations: Record<string, string>,
  options: { brandName?: string; brandLogoUrl?: string } = {}
): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const timesRoman = await pdfDoc.embedFont(StandardFonts.TimesRoman);
  const timesRomanBold = await pdfDoc.embedFont(StandardFonts.TimesRomanBold);

  let page = pdfDoc.addPage(PageSizes.Letter);
  const { width, height } = page.getSize();
  const margin = { top: 72, bottom: 72, left: 72, right: 72 };
  const lineHeight = 16;
  let y = height - margin.top;

  const write = (text: string, font = timesRoman, size = 11, customLineHeight = lineHeight) => {
    const lines = wrapText(text, width - margin.left - margin.right, font, size);
    for (const line of lines) {
      if (line === '') {
        y -= customLineHeight; // double space for paragraphs
        if (y < margin.bottom + 20) {
          page = pdfDoc.addPage(PageSizes.Letter);
          y = height - margin.top;
        }
        continue;
      }

      if (y < margin.bottom + 20) {
        page = pdfDoc.addPage(PageSizes.Letter);
        y = height - margin.top;
      }

      page.drawText(line, {
        x: margin.left,
        y,
        font,
        size,
        color: rgb(0.05, 0.1, 0.16),
      });
      y -= customLineHeight;
    }
  };

  // Title
  write(template.title.toUpperCase(), timesRomanBold, 14, 20);
  y -= 12;

  // Description
  write(template.description, timesRoman, 11, 16);
  y -= 12;

  for (const clause of template.clauses) {
    const isEnabled = enabledClauses[clause.id] ?? clause.enabledByDefault;
    if (!isEnabled && clause.optional) continue;

    if (clause.heading) {
      y -= 8;
      write(clause.heading, timesRomanBold, 11, 16);
    }

    const body = aiCustomizations[clause.id] ?? clause.body;
    const filled = interpolateFields(body, fieldValues);
    write(filled, timesRoman, 11, 16);
    y -= 4; // paragraph spacing
  }

  // Footer on all pages
  addFooter(pdfDoc, options.brandName ?? 'ContractHub', timesRoman);

  return pdfDoc.save();
}
